#%RAML 1.0
title: New API
description: |
  EXPOSE ORDERS
mediaType:
  - application/json
version: "0.1"
protocols:
  - HTTP
/getOrderById:
  /{id}:
    uriParameters:
      id:
        required: true
    get:
      displayName: getOrderById
      description: get Order by Id
      responses:
        "200":
          body: 
            application/json:
              example: !include responseOrder.json
                
      
